<a href="https://colab.research.google.com/github/submouse9903/test-1/blob/master/U47768_CH04_tensorBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [ ]:
type(i)

torch.Tensor

In [ ]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [ ]:
r1.dtype

torch.float32

In [ ]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2 
print(twos)

threes = ones + twos       # addition allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [ ]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[4.0845e-35, 0.0000e+00, 4.9231e-38],
         [0.0000e+00, 4.4842e-44, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 4.9231e-38],
         [0.0000e+00, 2.1707e-18, 4.5447e+30]]])
torch.Size([2, 2, 3])
tensor([[[-1.2569e-23,  4.5859e-41, -1.2569e-23],
         [ 4.5859e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  4.9207e-38],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.4216, 0.0691, 0.2332],
         [0.4047, 0.2162, 0.9927]],

        [[0.4128, 0.5938, 0.6128],
         [0.1519, 0.0453, 0.5035]]])


In [ ]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

In [ ]:
x = torch.rand(2,3)
y = torch.rand(3,4)

In [ ]:
x@y

tensor([[0.2283, 0.3617, 0.2450, 0.2374],
        [1.1728, 0.9648, 1.4286, 1.0833]])

In [ ]:
(x>0.5) | (x<0.3)

tensor([[ True,  True, False],
        [ True,  True,  True]])

In [ ]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

tensor([[0.9038, 0.5741],
        [0.7026, 0.3463]], requires_grad=True)


In [ ]:
b = a.clone()
print(b)

tensor([[0.9038, 0.5741],
        [0.7026, 0.3463]], grad_fn=<CloneBackward0>)


In [ ]:
c = a.detach().clone()
print(c)

tensor([[0.9038, 0.5741],
        [0.7026, 0.3463]])


In [ ]:
print(a)

tensor([[0.9038, 0.5741],
        [0.7026, 0.3463]], requires_grad=True)
