<a href="https://colab.research.google.com/github/submouse9903/test-1/blob/master/U47768_CH04_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
torch.manual_seed(1)
m = nn.Linear(3, 5)
input = torch.randn(4, 3)
output = m(input)
print(output.size())

torch.Size([4, 5])


In [ ]:
output

tensor([[-0.2807, -0.1942,  0.0709,  0.5529,  0.0128],
        [-0.4768, -0.3150,  0.2579,  0.6482, -0.1302],
        [ 0.1289, -0.2974, -0.2285,  0.4079,  0.2720],
        [-0.7977, -2.5335,  0.9189,  1.0357, -0.5763]],
       grad_fn=<AddmmBackward0>)

In [ ]:
m.weight

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462],
        [-0.1188,  0.2937,  0.0803],
        [-0.0707,  0.1601,  0.0285],
        [ 0.2109, -0.2250, -0.0421]], requires_grad=True)

In [ ]:
m.bias

Parameter containing:
tensor([-0.0520,  0.0837, -0.0023,  0.5047,  0.1797], requires_grad=True)

In [ ]:
m.bias + m.weight@input[0]

tensor([-0.4768, -0.3150,  0.2579,  0.6482, -0.1302], grad_fn=<AddBackward0>)

In [ ]:
p = 3
h1_dim = 5
out_dim =1

In [ ]:
model = nn.Sequential(nn.Linear(p, h1_dim),
                      nn.ReLU(),
                      nn.Linear(h1_dim, out_dim))
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
n = 10
x = torch.rand(n, p)
model(x)

tensor([[0.3960],
        [0.3844],
        [0.3722],
        [0.3854],
        [0.3771],
        [0.3690],
        [0.3840],
        [0.3893],
        [0.4003],
        [0.3872]], grad_fn=<SigmoidBackward0>)

In [ ]:
for name, param in model.named_parameters():
  print(name)
  print(param)

0.weight
Parameter containing:
tensor([[-0.3042,  0.2968, -0.3065],
        [ 0.1698, -0.1667, -0.0633],
        [-0.5551, -0.2753,  0.3133],
        [-0.1403,  0.5751,  0.4628],
        [-0.0270, -0.3854,  0.3516]], requires_grad=True)
0.bias
Parameter containing:
tensor([ 0.1792, -0.3732,  0.3750,  0.3505,  0.5120], requires_grad=True)
2.weight
Parameter containing:
tensor([[-0.2507, -0.0736, -0.0087,  0.0653, -0.3394]], requires_grad=True)
2.bias
Parameter containing:
tensor([-0.3174], requires_grad=True)


In [ ]:
# K-class classfication model
p=50
h1_dim = 20
h2_dim = 20
h3_dim = 20
out_dim = 10


model = nn.Sequential(nn.Linear(p, h1_dim),
                      nn.ReLU(),
                      nn.Linear(h1_dim, h2_dim),
                      nn.ReLU(),
                      nn.Linear(h2_dim, h3_dim),
                      nn.ReLU(),
                      nn.Linear(h3_dim, out_dim),
                      nn.Softmax(),
                      )
print(model)

Sequential(
  (0): Linear(in_features=50, out_features=20, bias=True)
  (1): ReLU()
  (2): Linear(in_features=20, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=20, bias=True)
  (5): ReLU()
  (6): Linear(in_features=20, out_features=10, bias=True)
  (7): Softmax(dim=None)
)


In [ ]:
n = 100
x = torch.rand(n,p)
model(x)[:5,:]

/usr/local/lib/python3.9/dist-packages/torch/nn/modules/container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


tensor([[0.0763, 0.0999, 0.0998, 0.0793, 0.0838, 0.1149, 0.0983, 0.1243, 0.1152,
         0.1081],
        [0.0793, 0.1009, 0.1005, 0.0786, 0.0848, 0.1136, 0.0986, 0.1229, 0.1151,
         0.1059],
        [0.0794, 0.0991, 0.1000, 0.0797, 0.0848, 0.1160, 0.0979, 0.1197, 0.1174,
         0.1060],
        [0.0782, 0.1005, 0.0999, 0.0789, 0.0842, 0.1157, 0.0986, 0.1216, 0.1158,
         0.1066],
        [0.0790, 0.0992, 0.1010, 0.0794, 0.0860, 0.1166, 0.0968, 0.1204, 0.1140,
         0.1075]], grad_fn=<SliceBackward0>)

In [ ]:
yhat = model(x)
yhat.shape

/usr/local/lib/python3.9/dist-packages/torch/nn/modules/container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


torch.Size([100, 10])

In [ ]:
torch.manual_seed(1)
torch.randint(0,out_dim,(n,))

tensor([5, 9, 4, 8, 3, 3, 1, 1, 9, 2, 8, 9, 6, 3, 3, 0, 2, 1, 2, 6, 0, 3, 6, 4,
        3, 6, 4, 2, 9, 4, 8, 6, 7, 3, 7, 3, 3, 6, 2, 0, 5, 9, 5, 3, 3, 5, 8, 9,
        1, 4, 4, 5, 8, 0, 1, 3, 1, 4, 7, 8, 6, 9, 9, 8, 3, 3, 1, 7, 2, 8, 9, 3,
        0, 2, 2, 8, 5, 9, 9, 0, 1, 2, 2, 5, 5, 0, 9, 1, 6, 9, 0, 8, 7, 7, 3, 2,
        7, 7, 2, 7])

In [ ]:
torch.manual_seed(1)
y = torch.randint(0,out_dim,(n,))
nn.functional.one_hot(y,10)[:5,:]

tensor([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])

In [ ]:
y = nn.functional.one_hot(y,out_dim)
y.shape

torch.Size([100, 10])

In [ ]:
yhat[0,:]

tensor([0.0763, 0.0999, 0.0998, 0.0793, 0.0838, 0.1149, 0.0983, 0.1243, 0.1152,
        0.1081], grad_fn=<SliceBackward0>)

In [ ]:
y[0,:]

tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
y[0,:]*torch.log(yhat[0,:])

tensor([-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -2.1636, -0.0000, -0.0000,
        -0.0000, -0.0000], grad_fn=<MulBackward0>)

In [ ]:
torch.sum(-y[0,:]*torch.log(yhat[0,:]))

tensor(2.1636, grad_fn=<SumBackward0>)

In [ ]:
torch.manual_seed(1)
y = torch.randint(0,out_dim,(n,))
cross_entropy_loss = nn.CrossEntropyLoss()
loss_value = cross_entropy_loss(yhat, y)
print(loss_value)

tensor(2.3036, grad_fn=<NllLossBackward0>)
